#!/usr/bin/env ruby

require "open-uri"
require "json"

class PinboardLinkImporter
  def call
    pinboard_data.map { |p| pinboard_post_as_link_attributes(p) }
  end

  private

  def pinboard_post_as_link_attributes(post)
    tags = post.fetch("tags").split(" ") - ["danott.co"]
    {
      title: post.fetch("description"),
      commentary: post.fetch("extended"),
      url: post.fetch("href"),
      date: post.fetch("time"),
      hash: post.fetch("hash"),
      tags: tags,
    }
  end

  def pinboard_data
    auth_token = ENV["PINBOARD_AUTH_TOKEN"]
    url = "https://api.pinboard.in/v1/posts/all?tag=danott.co&format=json&auth_token=#{auth_token}"
    JSON.load(strip_byte_order_mark(URI.open(url).read))
  end

  def strip_byte_order_mark(potentially_unparsable)
    potentially_unparsable.dup.sub("\xEF\xBB\xBF".force_encoding("UTF-8"), "")
  end
end

links = PinboardLinkImporter.new.call
puts JSON.dump(links)
